---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-deployment
  namespace: sampleapp
  labels:
    app: sampleapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: sampleapp
          image: <REGISTRY>/<ECR_REPOSITORY>:v0
          ports:
            - containerPort: 8000
          env:
            - name: HOGE
              value: "hogevalue"

